spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pplax_blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 2835
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: xyz.pplax.pplaxblog.xo.entity
  mapper-locations: classpath*:mapper/*.xml
