#app
server:
  port: 4393

#spring
spring:
  application:
    name: file-server
  thymeleaf:
    cache: true   #关闭缓存
  devtools:
    restart:
      enabled: false #启动热部署
      additional-paths:
        - src/main/java #设置重启的目录，添加哪个目录文件需要restart

  # 配置文件上传大小限制
  servlet:
    multipart:
      # 最大文件的大小
      max-file-size: 100MB
      # 最大请求大小
      max-request-size: 150MB
      # 是否启用分段上传支持
      enabled: true
      #上传文件的中间位置
      location: G:/tmp/pplax-log/pplax-file/tomcat_upload_temp

  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl     #打印sql日志
##logging
logging:
  root:
    level: warn

