#app
server:
  port: 8082

#spring
spring:
  application:
    name: auth-server
  thymeleaf:
    cache: true   #关闭缓存
  devtools:
    restart:
      enabled: false #启动热部署
      additional-paths:
        - src/main/java #设置重启的目录，添加哪个目录文件需要restart

  # DATABASE CONFIG
  datasource:
    url: jdbc:mysql://localhost:3306/pplax_blog?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false

  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl     #打印sql日志
##logging
logging:
  root:
    level: warn

#[{"key":"client_id","value":"admin","equals":true,"description":"","enabled":true},{"key":"client_secret","value":"admin123456","equals":true,"description":"","enabled":true},{"key":"grant_type","value":"password","equals":true,"description":"","enabled":true},{"key":"password","value":"123456","equals":true,"description":"","enabled":true},{"key":"username","value":"lucky","equals":true,"description":"","enabled":true}]