#app
server:
  port: 8082

#spring
spring:
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password: 123456
  application:
    name: auth-server
  thymeleaf:
    cache: true   #关闭缓存
  devtools:
    restart:
      enabled: false #启动热部署
      additional-paths:
        - src/main/java #设置重启的目录，添加哪个目录文件需要restart

  # DATABASE CONFIG
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pplax_blog?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: xyz.pplax.pplaxblog.xo.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: UUID
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl     #打印sql日志
##logging
logging:
  root:
    level: warn

# 自定义配置
pplax:
  api:
    base-path: /api   # 统一父级请求路径
  sso:
    admin:
      client-id: admin
      client-secret: admin123456
      resource-id: admin-server
      redirect-uri: http://127.0.0.1:8081/callback.html
# http://localhost:8082/oauth/authorize?client_id=admin&client_secret=admin123456t&response_type=code&redirect_uri=http://127.0.0.1:8081/callback.html
# http://localhost:8082/oauth/token
#[{"key":"client_id","value":"admin","equals":true,"description":"","enabled":true},{"key":"client_secret","value":"admin123456","equals":true,"description":"","enabled":true},{"key":"grant_type","value":"password","equals":true,"description":"","enabled":true},{"key":"password","value":"123456","equals":true,"description":"","enabled":true},{"key":"username","value":"lucky","equals":true,"description":"","enabled":true}]