server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  profiles:
#    active: dev
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

springdoc:
  swagger-ui:
    use-root-path: true