server:
  port: 8084
spring:
#  profiles:
#    active: dev
  cloud:
    bootstrap:
      enable: true
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher